spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: blog
      username: root
      password: example
      authentication-database: admin
      uri: mongodb://localhost:27017/blog?retryWrites=false